### ISSUE TITLE
As I said

### ISSUE THREAD

**Issue by Genzer** [frystalizer/cv#1]
I would still prefer using `@BeforeEach` as:

(1) it is a JUnit construct for running tests. JUnit will ensure `@BeforeEach` runs in a correct sequence order (e.g inherits from parent test class, etc).

(2) make it consistent with method annotated with `@AfterEach` to form a full cycle of a test.

(3) Can make use of JUnit extensions (ParameterResolver).

(4) Will work correctly if `@TestInstance` is changed from PER_METHOD (default) to PER_CLASS.

**Comment by frystalizer** [comment]
TL;DR Won't fix
